name : Build and upload artifact
on : workflow_dispatch
jobs : 
  Build :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout code
        uses : actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: src/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/package-lock.json') }}
      - name : Install dependencies
        run : npm install
        working-directory: src/
      - name : Build
        run: npm run build
        working-directory: src/
      - name : Upload artifact
        uses : actions/upload-artifact@v4
        with:
            name: game-build-${{ github.sha }}
            path: src/dist/
